#
# 这个文档包含了本博客的设定信息，你可以编辑它来个性化自己的博客，
#

# 你的博客名称，请用你想要的博客名替换“LOFFER”，以下修改都可类似处理
# 注意，“name: LOFFER”，冒号后面的空格不可以省略。
# 井号后面的文字是说明文档，不会被程序读取。

# 描述/签名
name: Laura Lungu
description: I use the Drosophila larva brain connectome to study multisensory integration from behaviour to genes, discovering how neural circuit structure relates to function.

#Enter your website domain name (if you did not add your own domain name, but directly use the domain name assigned by GitHub pages, you can omit it) 
url: wordsonflies.xyz

baseurl: /


#
# The following settings are optional
#

# Your blog logo image URL, the recommended size should not exceed 300px × 300px
avatar: https://raw.githubusercontent.com/whiteflies/WordsOnFlies_2/master/images/fly2.png

# Your favicon (appearing on the browser tab) image URL, it is recommended to use a smaller (64px × 64px) image
favicon: https://raw.githubusercontent.com/whiteflies/WordsOnFlies_2/master/images/fly2.png


# Buttons in the menu
navigation:
  - name: Home
    url: /wordsonflies.xyz
  - name: About
    url: /about
  - name: Publications
    url: /archive
  - name: CV
    url: /tags

# Number of articles per page
paginate: 8

# Distinction mark for article introduction
excerpt_separator: <!-- more -->

# Your social network links, they will appear as icons in the footer of your website, optional
footer-links: 
  weibo:  #请输入你的微博个性域名 https://www.weibo.com/<thispart>
  behance: # https://www.behance.net/<>
  dribbble: # https://dribbble.com/<>
  email: laura.lungum@gmail.com
  facebook: #https://www.facebook.com/<>
  flickr: #https://www.flickr.com/<>
  github: FromEndWorld/loffer #https://github.com/<>
  instagram: #https://instagram.com/<>
  linkedin: https://www.linkedin.com/in/laura-lungu-907616135/
  pinterest: #https://www.pinterest.com/<>
  rss: #随便填点啥RSS就能用了
  stackoverflow: # http://stackoverflow.com/<>
  tumblr: # https://<username>.tumblr.com
  twitter: https://twitter.com/LauraLungum
  youtube: # channel/<your_long_string> or user/<user-name>
  orcid: https://orcid.org/0000-0002-3186-0949

# Site footer text
footer-text: Copyright (c) 2019 来自中世界

#
# Comment, note, please don’t add multiple comment areas at the same time
#

# Enter Disqus shortname to add a comment area, please refer to the documentation, set up your own disqus site, and do not continue to use my site loffer
disqus: loffer #shortname

# Enter Gitalk related settings to add a comment area, please see the tutorial for details
gitalk:
  clientID: 
  clientSecret: 
  repo: 
  owner: 

# 输入Google Analytics web tracking code
google_analytics:

utteranc:
  repo: # Your github repo path, also see: https://utteranc.es

#
# !! All the following settings do not need to be changed !!
#

permalink: /:title/
paginate_path: /page:num/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

